services:
  app:
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=YourDatabase;User=sa;Password=YourStrong@Password
      - Redis__Connection=redis:6379
    depends_on:
      - redis
      - sqlserver

  redis:
    image: "redis:6.2"
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "YourRedisPassword"]

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"