services:
  app:
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - "5000:5000"
      # - "5001:443"
    # environment:
      # - DockerConnectionStrings__SqlConnectionString=Server=sql_server2022;Database=SalesDb;MultipleActiveResultSets=true
      # - DockerConnectionStrings__RedisConnectionString=localhost:6379,abortConnect=false
    depends_on:
      # - redis
      - sqlserver

  # redis:
  #   image: "redis:6.2"
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   command: ["redis-server"]

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    environment:
      SA_PASSWORD: SA#@Complex#@Password__.123
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"